"""Developer-only paths and hyperparameters for DeBERTa/LoRA training."""

from developer.config import (
    EXPERIMENT_LORA_DIR,
    EXPERIMENT_PRETRAIN_DIR,
    MODELS_DIR,
    PRETRAIN_CORPUS_DIR,
    SUPERVISED_CORPUS_DIR,
    SUPERVISED_SPLITS_DIR,
)
from user_app.inference.contract import ID2LABEL, LABEL2ID, MAX_LENGTH, NUM_LABELS


INPUT_DIR = str(SUPERVISED_CORPUS_DIR)
PRETRAIN_INPUT_CSV = str(PRETRAIN_CORPUS_DIR / "pretrain_flows.csv")
SUPERVISED_INPUT_CSV = str(SUPERVISED_CORPUS_DIR / "supervised_flows.csv")
PRETRAIN_FLOWS_JSONL = str(PRETRAIN_CORPUS_DIR / "pretrain_flows.jsonl")
SUPERVISED_FLOWS_JSONL = str(SUPERVISED_CORPUS_DIR / "supervised_flows.jsonl")
TRAIN_JSONL = str(SUPERVISED_SPLITS_DIR / "train.jsonl")
VAL_JSONL = str(SUPERVISED_SPLITS_DIR / "val.jsonl")
TEST_JSONL = str(SUPERVISED_SPLITS_DIR / "test.jsonl")

MODEL_DIR = str(MODELS_DIR / "deberta-v3-base")
PRETRAIN_DIR = str(EXPERIMENT_PRETRAIN_DIR)
LORA_DIR = str(EXPERIMENT_LORA_DIR)

PRETRAIN_MAX_LENGTH = 256
PRETRAIN_BATCH_SIZE = 1
PRETRAIN_EPOCHS = 5
PRETRAIN_EARLY_STOP_PATIENCE = 2
PRETRAIN_MIN_DELTA = 1e-4
PRETRAIN_LR = 3e-5
PRETRAIN_WARMUP = 1000

LORA_BATCH_SIZE = 2
LORA_GRAD_ACCUM_STEPS = 8
LORA_EPOCHS = 20
LORA_EARLY_STOP_PATIENCE = 3
LORA_MIN_DELTA = 1e-4
LORA_LR = 2e-4
LORA_R = 8
LORA_ALPHA = 16
LORA_DROPOUT = 0.1
LORA_TARGET_MODULES = ["query_proj", "value_proj", "key_proj"]

SEED = 42
TRAIN_RATIO = 0.6
VAL_RATIO = 0.2
